# RT-N14U board.mk

BOARD_NAME = RT-N14U

# Kernel
CONFIG_MT7620 = y
CONFIG_RALINK_RT3052 = n
CONFIG_RALINK_RT3352 = n
CONFIG_RALINK_RT5350 = n
CONFIG_RALINK_RT6855 = n

# CPU
CONFIG_CPU_MIPS32_R2 = y
CONFIG_CPU_LITTLE_ENDIAN = y

# Network (ВАЖНО ДЛЯ ПИНГА)
CONFIG_RA_NAT_HW = y
CONFIG_RA_HW_NAT_IPV6 = y
CONFIG_RT2860V2_AP_HW_ANTENNA_DIVERSITY = n
CONFIG_RT2860V2_AP_ANTENNA_DIVERSITY = n

# Настройка свитча для MT7620
CONFIG_RAETH_ESW = y
CONFIG_RAETH_HAS_PORT5 = n
