# RT-N14U board.mk

BOARD_NAME = RT-N14U

# Kernel
CONFIG_MT7620 = y
CONFIG_RALINK_RT3052 = n
CONFIG_RALINK_RT3352 = n
CONFIG_RALINK_RT5350 = n
CONFIG_RALINK_RT6855 = n

# CPU
CONFIG_CPU_MIPS32_R2 = y
CONFIG_CPU_LITTLE_ENDIAN = y

# Network
CONFIG_RA_NAT_HW = y
CONFIG_RA_HW_NAT_IPV6 = y
